
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sriyo
 */
public class Cart extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    String st;
    public Cart() {
        initComponents();
    }

    
    public Cart(ArrayList<String> list1,ArrayList<String> list2,ArrayList<String> list3,String t,String st1 ) {
        initComponents();
        String total=t;
        st=st1;
        ArrayList<String> plist=new ArrayList<String>();
        ArrayList<String> blist=new ArrayList<String>();
        ArrayList<String> mlist=new ArrayList<String>();
        plist=list1;
        blist=list2;
        mlist=list3;
        int x=1;
        DefaultTableModel model = (DefaultTableModel) 
        jTable1.getModel();
        try{
        for(int j=0;j<plist.size();j++)
        {
            model.addRow (new Object[] {x,blist.get(j),mlist.get(j),plist.get(j)}); 
            x++;
        }
        jTextField1.setText(total);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr.No", "BRAND", "MODEL", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("PROCEED TO PAYMENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CONTINUE SHOPPING");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("GRAND TOTAL");

        jTextField1.setEditable(false);

        jButton3.setText("DELETE ITEM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Your Shopping Cart");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    new Menu(st).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try{
        int s=jTable1.getSelectedRow();
       DefaultTableModel model = (DefaultTableModel) 
       jTable1.getModel();
       Object ob = jTable1.getModel().getValueAt(s, 2);
       String m=ob.toString();
       try
            {
        Class.forName("java.sql.DriverManager");
        Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/e_store", "root","Sriyog123");
        Statement stmt = (Statement) con.createStatement();
        Statement stmt1 = (Statement) con.createStatement();
        Statement stmt2 = (Statement) con.createStatement();
        Statement stmt3 = (Statement) con.createStatement();
        String query="Select item_no from electronic_item where model='"+m+"';";
        ResultSet rs=stmt.executeQuery(query);
        if(rs.next())
        {
            String it=rs.getString("item_no");
            String query1="delete from cart1 where item_no='"+it+"';";
            stmt.executeUpdate(query1);
            
            String query2="Select SUM(I_Price) as total  from Cart1 where Cart_ID='"+st+"';";
             ResultSet rs2=stmt1.executeQuery(query2);
           if(rs2.next())
            {
                String tot=rs2.getString("total");
                 String query3="Update Cart set Price='"+tot+"' where Cart_ID='"+st+"';";
                stmt1.executeUpdate(query3);
                
                String query4="Select count(Cart_ID) as quan  from Cart1 where Cart_ID='"+st+"';";
                ResultSet rs4=stmt2.executeQuery(query4);
                
                if(rs4.next())
                {
                      String c=rs4.getString("quan");
                       String query5="Update Cart set Quantity='"+c+"' where Cart_ID='"+st+"';";
                        stmt2.executeUpdate(query5);
                        
                
            
            String query15=" Select I_Price from Cart1 where Cart_ID in(select cart_id from cart1 group by cart_id having count(*)>0 and cart_id='"+st+"');";
            ResultSet rs5=stmt3.executeQuery(query15);
            rs5=stmt3.getResultSet();
           
            ArrayList<String> list2=new ArrayList<String>();
            String ip="";
            while(rs5.next())
            {
                ip=rs5.getString("I_price");
                list2.add(ip);
                
            } 
             String query6=" Select Electronic_item.Brand from Cart1,Electronic_item where cart1.item_no=electronic_item.item_no and cart1.Cart_ID in(select cart_id from cart1 group by cart_id having count(*)>0 and cart_id='"+st+"');";
            ResultSet rs6=stmt3.executeQuery(query6);
            rs6=stmt3.getResultSet();
            
            ArrayList<String> list1=new ArrayList<String>();
            String b1="";
            while(rs6.next())
            {
                b1=rs6.getString("Electronic_item.brand");
                list1.add(b1);
                
            }  
            String query7="Select Electronic_item.model from Cart1,Electronic_item where cart1.item_no=electronic_item.item_no and cart1.Cart_ID in(select cart_id from cart1 group by cart_id having count(*)>0 and cart_id='"+st+"');";
            ResultSet rs7=stmt3.executeQuery(query7);
            rs7=stmt3.getResultSet();
            
            ArrayList<String> list=new ArrayList<String>();
            String m1="";
            while(rs7.next())
            {
                m1=rs7.getString("Electronic_item.model");
                list.add(m1);
                
            }    
             
            

            int rows=model.getRowCount();
                if (rows>0)
                {
                for (int i=0; i<rows; i++)
                model.removeRow(0);
                }
            int x=1;
            for(int i=0;i<list.size();i++)
            {
                 model.addRow (new Object[] {x,list1.get(i),list.get(i),list2.get(i)}); 
                     x++;
            }
             String query8="Select Price from Cart where cart_id='"+st+"';";
            ResultSet rs8=stmt3.executeQuery(query8);
            
            if(rs8.next())
            {
                String gp=rs8.getString("Price");
                jTextField1.setText(gp);
            }
        }
    }
            
            
            
            }
        JOptionPane.showMessageDialog(this,"Selected Item Has Been Removed");
           }
       catch(Exception e)
       {
           System.out.println(e);
       }
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,"Please select the item to be removed");
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try
            {
        Class.forName("java.sql.DriverManager");
        Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/e_store", "root","Sriyog123");
        Statement stmt = (Statement) con.createStatement();
        String query="Select user_id from cart where cart_id='"+st+"';";
        ResultSet rs=stmt.executeQuery(query);
        String a=jTextField1.getText();
        if(rs.next())
        {
            String u=rs.getString("user_id");
            new Payment(u,a,st).setVisible(true);
            this.dispose();
        }
            }
       catch(Exception e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
